import { Match } from "./match";

export const MATCHES: Match[]=[
    {
        id: "1",
        teama:'ind',
        imagea: '/assets/images/India.png',
        teamb:'pak',
        imageb: '/assets/images/Pakistan.png',
        date:null,
        location:'Hyderabad',
        matchtype:'T20-international',
        battingteam:'ind',
        winner:'0',
        status:'India Batting',
        live:true,
        aovers :20,
        aruns :106,
        awickets :2,
        bovers :0,
        bruns :0,
        bwickets :0,
        adata:[1,2,3,4],
        bdata:[1,2,3,4]
    },
    {
        id: "2",
        teama:'eng',
        imagea: '/assets/images/England.png',
        teamb:'pak',
        imageb: '/assets/images/Pakistan.png',
        date:null,
        location:'Hyderabad',
        matchtype:'ODI (One-Day International)',
        battingteam:'pak',
        winner:'a',
        status:'Eng won',
        live:false,
        aovers :20,
        aruns :106,
        awickets :2,
        bovers :20,
        bruns :105,
        bwickets :10,
        adata:[1,2,3,4],
        bdata:[1,2,3,4]
    },
    {
        id: "3",
        teama:'ind',
        imagea: '/assets/images/India.png',
        teamb:'eng',
        imageb: '/assets/images/England.png',
        date:null,
        location:'Hyderabad',
        matchtype:'Test Cricket',
        battingteam:'ind',
        winner:'d',
        status:'Draw Match',
        live:false,
        aovers :20,
        aruns :106,
        awickets :10,
        bovers :20,
        bruns :106,
        bwickets :10,
        adata:[1,2,3,4],
        bdata:[1,2,3,4]
    }
]